// cmd/audit-v775/scope_reports.go — report writers for the
// structural scope audit. Split out of scope.go to keep each file
// under the 300-line budget. All three report kinds
// (production markdown, test markdown, evidence JSON) live here.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
)

func writeReports(ev map[string]*evidence) {
	_ = os.MkdirAll("audits", 0755)
	all := make([]*evidence, 0, len(ev))
	for _, e := range ev {
		all = append(all, e)
	}
	sort.Slice(all, func(i, j int) bool { return all[i].File < all[j].File })
	writeProductionMD(all)
	writeTestMD(all)
	writeJSON(all)
}

func writeProductionMD(all []*evidence) {
	path := "audits/v7.75-structural-scope.md"
	f, err := os.Create(path)
	if err != nil {
		fatal("create %s: %v", path, err)
	}
	defer f.Close()
	fmt.Fprintln(f, "# v7.75 Provenance — Production File Scope")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "Generated by `cmd/audit-v775 scope`. Do not edit by hand.")
	fmt.Fprintln(f, "")
	inScope, reviewOnly := 0, 0
	for _, e := range all {
		if e.IsTest {
			continue
		}
		if e.Disposition == "in-scope" {
			inScope++
		} else {
			reviewOnly++
		}
	}
	fmt.Fprintf(f, "## Summary\n\n- In-scope: %d\n- Review-only: %d\n\n", inScope, reviewOnly)
	fmt.Fprintln(f, "## Files")
	fmt.Fprintln(f, "")
	for _, e := range all {
		if e.IsTest {
			continue
		}
		fmt.Fprintf(f, "### `%s` — %s\n\n", e.File, e.Disposition)
		for _, r := range e.Rationale {
			fmt.Fprintf(f, "- %s\n", r)
		}
		fmt.Fprintln(f, "")
	}
}

func writeTestMD(all []*evidence) {
	path := "audits/v7.75-test-scope.md"
	f, err := os.Create(path)
	if err != nil {
		fatal("create %s: %v", path, err)
	}
	defer f.Close()
	fmt.Fprintln(f, "# v7.75 Provenance — Test Scope")
	fmt.Fprintln(f, "")
	count := 0
	for _, e := range all {
		if e.IsTest {
			count++
		}
	}
	fmt.Fprintf(f, "## Summary\n\n- Test files in scope: %d\n\n", count)
	fmt.Fprintln(f, "## Files")
	fmt.Fprintln(f, "")
	for _, e := range all {
		if !e.IsTest {
			continue
		}
		fmt.Fprintf(f, "### `%s`\n\n", e.File)
		for _, r := range e.Rationale {
			fmt.Fprintf(f, "- %s\n", r)
		}
		fmt.Fprintln(f, "")
	}
}

func writeJSON(all []*evidence) {
	path := "audits/v7.75-evidence.json"
	f, err := os.Create(path)
	if err != nil {
		fatal("create %s: %v", path, err)
	}
	defer f.Close()
	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	if err := enc.Encode(all); err != nil {
		fatal("encode json: %v", err)
	}
}
